steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _GOOGLE_CLIENT_ID: ""
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/lockin/app:latest
options:
  logging: CLOUD_LOGGING_ONLY
