"""Create the initial LockIn schema.

Explicit DDL rather than a metadata.create_all() wrapper, so later revisions can
be autogenerated against a known baseline and reviewed as diffs.
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

TEAM_ROLE = sa.Enum("ADMIN", "MEMBER", name="teamrole")
MEMBERSHIP_STATUS = sa.Enum("ACTIVE", "REMOVED", name="membershipstatus")
CHALLENGE_STATUS = sa.Enum(
    "DRAFT", "UPCOMING", "ACTIVE", "COMPLETED", name="challengestatus"
)
PARTICIPANT_STATUS = sa.Enum(
    "ACTIVE", "REMOVED", "COMPLETED", "FORFEIT_DUE", name="participantstatus"
)
GOAL_CATEGORY = sa.Enum(
    "ISLAMIC", "PHYSICAL", "CAREER", "BUSINESS", "PERSONAL", name="goalcategory"
)
TRACKING_TYPE = sa.Enum("MILESTONE", "NUMERIC", "COUNT", "MANUAL", name="trackingtype")
TARGET_DIRECTION = sa.Enum("AT_LEAST", "AT_MOST", name="targetdirection")
GOAL_VISIBILITY = sa.Enum("TEAM", "PRIVATE", name="goalvisibility")
FORFEIT_TYPE = sa.Enum("PER_OTHER_MEMBER", name="forfeittype")
OBLIGATION_STATUS = sa.Enum("OUTSTANDING", "SETTLED", name="obligationstatus")
NOTIFICATION_TYPE = sa.Enum(
    "GOALS_DUE_SOON",
    "GOALS_LOCK_TOMORROW",
    "GOALS_LOCKED",
    "CHALLENGE_MILESTONE",
    "CHALLENGE_COMPLETE",
    "MEMBER_COMPLETED_GOAL",
    "MEMBER_JOINED",
    name="notificationtype",
)

ENUMS = [
    TEAM_ROLE,
    MEMBERSHIP_STATUS,
    CHALLENGE_STATUS,
    PARTICIPANT_STATUS,
    GOAL_CATEGORY,
    TRACKING_TYPE,
    TARGET_DIRECTION,
    GOAL_VISIBILITY,
    FORFEIT_TYPE,
    OBLIGATION_STATUS,
    NOTIFICATION_TYPE,
]

NOW = sa.text("now()")


def timestamp(name: str) -> sa.Column:
    """A server-defaulted, non-null timestamp column."""
    return sa.Column(
        name, sa.DateTime(timezone=True), server_default=NOW, nullable=False
    )


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("google_sub", sa.String(255), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=False),
        sa.Column("avatar_url", sa.String(2048), nullable=True),
        timestamp("created_at"),
        timestamp("updated_at"),
    )
    op.create_index("ix_users_google_sub", "users", ["google_sub"], unique=True)
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("created_by", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        timestamp("created_at"),
    )

    op.create_table(
        "team_members",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "team_id",
            sa.Uuid(),
            sa.ForeignKey("teams.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", TEAM_ROLE, nullable=False),
        sa.Column("status", MEMBERSHIP_STATUS, nullable=False),
        timestamp("joined_at"),
        sa.UniqueConstraint("team_id", "user_id", name="uq_team_members_team_user"),
    )
    op.create_index("ix_team_members_team_id", "team_members", ["team_id"])
    op.create_index("ix_team_members_user_id", "team_members", ["user_id"])

    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "team_id",
            sa.Uuid(),
            sa.ForeignKey("teams.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("code_hash", sa.String(255), nullable=False),
        sa.Column("code_prefix", sa.String(4), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        timestamp("created_at"),
    )
    op.create_index("ix_invitations_team_id", "invitations", ["team_id"])

    op.create_table(
        "challenges",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "team_id",
            sa.Uuid(),
            sa.ForeignKey("teams.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(64), nullable=False),
        sa.Column("goal_submission_days", sa.Integer(), nullable=False),
        sa.Column("forfeit_type", FORFEIT_TYPE, nullable=False),
        sa.Column("forfeit_amount_pence", sa.Integer(), nullable=False),
        sa.Column("status", CHALLENGE_STATUS, nullable=False),
        timestamp("created_at"),
    )
    op.create_index("ix_challenges_team_id", "challenges", ["team_id"])

    op.create_table(
        "challenge_participants",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "challenge_id",
            sa.Uuid(),
            sa.ForeignKey("challenges.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("goals_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("goals_locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("goals_committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", PARTICIPANT_STATUS, nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint(
            "challenge_id", "user_id", name="uq_participants_challenge_user"
        ),
    )
    op.create_index(
        "ix_challenge_participants_challenge_id",
        "challenge_participants",
        ["challenge_id"],
    )
    op.create_index(
        "ix_challenge_participants_user_id", "challenge_participants", ["user_id"]
    )

    op.create_table(
        "goals",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "challenge_participant_id",
            sa.Uuid(),
            sa.ForeignKey("challenge_participants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "parent_goal_id",
            sa.Uuid(),
            sa.ForeignKey("goals.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("category", GOAL_CATEGORY, nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tracking_type", TRACKING_TYPE, nullable=False),
        sa.Column("baseline_value", sa.Numeric(16, 4), nullable=True),
        sa.Column("target_value", sa.Numeric(16, 4), nullable=True),
        sa.Column("current_value", sa.Numeric(16, 4), nullable=True),
        sa.Column("unit", sa.String(64), nullable=True),
        sa.Column("target_direction", TARGET_DIRECTION, nullable=True),
        sa.Column("manual_progress_percentage", sa.Integer(), nullable=True),
        sa.Column("visibility", GOAL_VISIBILITY, nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        timestamp("created_at"),
        timestamp("updated_at"),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_goals_challenge_participant_id", "goals", ["challenge_participant_id"]
    )
    op.create_index("ix_goals_parent_goal_id", "goals", ["parent_goal_id"])

    op.create_table(
        "goal_progress_entries",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "goal_id",
            sa.Uuid(),
            sa.ForeignKey("goals.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("numeric_value", sa.Numeric(16, 4), nullable=True),
        sa.Column("numeric_delta", sa.Numeric(16, 4), nullable=True),
        sa.Column("manual_percentage", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("evidence_url", sa.String(2048), nullable=True),
        timestamp("created_at"),
    )
    op.create_index(
        "ix_progress_goal_date", "goal_progress_entries", ["goal_id", "entry_date"]
    )
    op.create_index(
        "ix_progress_user_date", "goal_progress_entries", ["user_id", "entry_date"]
    )

    op.create_table(
        "daily_checkins",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "challenge_participant_id",
            sa.Uuid(),
            sa.ForeignKey("challenge_participants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("checkin_date", sa.Date(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        timestamp("created_at"),
        timestamp("updated_at"),
        sa.UniqueConstraint(
            "challenge_participant_id",
            "checkin_date",
            name="uq_checkin_participant_day",
        ),
    )
    op.create_index(
        "ix_daily_checkins_challenge_participant_id",
        "daily_checkins",
        ["challenge_participant_id"],
    )

    op.create_table(
        "challenge_outcomes",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "challenge_participant_id",
            sa.Uuid(),
            sa.ForeignKey("challenge_participants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("required_goals_total", sa.Integer(), nullable=False),
        sa.Column("required_goals_completed", sa.Integer(), nullable=False),
        sa.Column("optional_goals_total", sa.Integer(), nullable=False),
        sa.Column("optional_goals_completed", sa.Integer(), nullable=False),
        sa.Column("final_progress_percentage", sa.Numeric(5, 2), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("total_forfeit_pence", sa.Integer(), nullable=False),
        timestamp("evaluated_at"),
        sa.UniqueConstraint("challenge_participant_id", name="uq_outcome_participant"),
    )

    op.create_table(
        "forfeit_obligations",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "challenge_id", sa.Uuid(), sa.ForeignKey("challenges.id"), nullable=False
        ),
        sa.Column("from_user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("to_user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("amount_pence", sa.Integer(), nullable=False),
        sa.Column("status", OBLIGATION_STATUS, nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        timestamp("created_at"),
        sa.UniqueConstraint(
            "challenge_id",
            "from_user_id",
            "to_user_id",
            name="uq_forfeit_challenge_from_to",
        ),
    )

    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "challenge_id",
            sa.Uuid(),
            sa.ForeignKey("challenges.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("type", NOTIFICATION_TYPE, nullable=False),
        sa.Column("dedupe_key", sa.String(255), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("body", sa.String(500), nullable=True),
        sa.Column("link_path", sa.String(500), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        timestamp("created_at"),
        sa.UniqueConstraint(
            "user_id", "type", "dedupe_key", name="uq_notification_dedupe"
        ),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "actor_user_id", sa.Uuid(), sa.ForeignKey("users.id"), nullable=False
        ),
        sa.Column(
            "team_id",
            sa.Uuid(),
            sa.ForeignKey("teams.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("entity_type", sa.String(100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        timestamp("created_at"),
    )
    op.create_index("ix_audit_logs_team_id", "audit_logs", ["team_id"])


def downgrade() -> None:
    for table in (
        "audit_logs",
        "notifications",
        "forfeit_obligations",
        "challenge_outcomes",
        "daily_checkins",
        "goal_progress_entries",
        "goals",
        "challenge_participants",
        "challenges",
        "invitations",
        "team_members",
        "teams",
        "users",
    ):
        op.drop_table(table)
    bind = op.get_bind()
    for enum_type in ENUMS:
        enum_type.drop(bind, checkfirst=True)
